"""initial schema

Revision ID: e2e1eb75e9ee
Revises:
Create Date: 2026-07-23 12:24:57.442772

Hand-written (not autogenerated) — mirrors models/*.py exactly. See
Optimization/analysis notes in the app's conversation history for the
entity-relationship rationale: candidates is the root; resume_uploads and
audit_results hang off it 1:1 / 1:many; audit_category_scores and
audit_findings hang off audit_results.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2e1eb75e9ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "candidates",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("full_name", sa.String(255), nullable=False, server_default=""),
        sa.Column("email", sa.String(255), nullable=False, server_default=""),
        sa.Column("phone", sa.String(50), nullable=False, server_default=""),
        sa.Column("location", sa.String(255), nullable=False, server_default=""),
        sa.Column("college", sa.String(255), nullable=False, server_default=""),
        sa.Column("degree", sa.String(255), nullable=False, server_default=""),
        sa.Column("branch", sa.String(255), nullable=False, server_default=""),
        sa.Column("grad_year", sa.String(20), nullable=False, server_default=""),
        sa.Column("cgpa", sa.String(20), nullable=False, server_default=""),
        sa.Column("target_role", sa.String(255), nullable=False),
        sa.Column("experience_level", sa.String(50), nullable=False),
        sa.Column("linkedin_url", sa.String(500), nullable=False, server_default=""),
        sa.Column("github_url", sa.String(500), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_candidates_email", "candidates", ["email"])
    op.create_index("ix_candidates_college", "candidates", ["college"])
    op.create_index("ix_candidates_target_role", "candidates", ["target_role"])
    op.create_index("ix_candidates_experience_level", "candidates", ["experience_level"])
    op.create_index("ix_candidates_created_at", "candidates", ["created_at"])

    op.create_table(
        "candidate_skills",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "candidate_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("candidates.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("skill", sa.String(100), nullable=False),
        sa.UniqueConstraint("candidate_id", "skill", name="uq_candidate_skill"),
    )
    op.create_index("ix_candidate_skills_candidate_id", "candidate_skills", ["candidate_id"])
    op.create_index("ix_candidate_skills_skill", "candidate_skills", ["skill"])

    op.create_table(
        "resume_uploads",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "candidate_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("candidates.id", ondelete="CASCADE"), nullable=False, unique=True,
        ),
        sa.Column("file_name", sa.String(500), nullable=False),
        sa.Column("storage_path", sa.String(1000), nullable=False),
        sa.Column("raw_extracted_text", sa.Text(), nullable=False, server_default=""),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_resume_uploads_candidate_id", "resume_uploads", ["candidate_id"], unique=True)

    op.create_table(
        "audit_results",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "candidate_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("candidates.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("overall_score", sa.SmallInteger(), nullable=False),
        sa.Column("recruiter_7sec_scan", sa.String(10), nullable=False),
        sa.Column("ats_risk_level", sa.String(10), nullable=False),
        sa.Column("keyword_gaps", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("passed_checks", postgresql.JSONB(), nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column("bullet_count", sa.SmallInteger(), nullable=False, server_default="0"),
        sa.Column("page_count", sa.SmallInteger(), nullable=False, server_default="0"),
        sa.Column("file_name", sa.String(500), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_audit_results_candidate_id", "audit_results", ["candidate_id"])
    op.create_index("ix_audit_results_overall_score", "audit_results", ["overall_score"])
    op.create_index("ix_audit_results_recruiter_7sec_scan", "audit_results", ["recruiter_7sec_scan"])
    op.create_index("ix_audit_results_ats_risk_level", "audit_results", ["ats_risk_level"])
    op.create_index("ix_audit_results_created_at", "audit_results", ["created_at"])

    op.create_table(
        "audit_category_scores",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "audit_result_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("audit_results.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("category", sa.String(50), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=False),
        sa.UniqueConstraint("audit_result_id", "category", name="uq_audit_category"),
    )
    op.create_index("ix_audit_category_scores_audit_result_id", "audit_category_scores", ["audit_result_id"])

    op.create_table(
        "audit_findings",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "audit_result_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("audit_results.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("severity", sa.String(10), nullable=False),
        sa.Column("category", sa.String(100), nullable=False),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False, server_default=""),
        sa.Column("why_it_matters", sa.Text(), nullable=False, server_default=""),
        sa.Column("location", sa.String(255), nullable=False, server_default=""),
        sa.Column("action", sa.Text(), nullable=False, server_default=""),
        sa.Column("original_text", sa.Text(), nullable=True),
        sa.Column("suggested_fix", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False, server_default="0"),
    )
    op.create_index("ix_audit_findings_audit_result_id", "audit_findings", ["audit_result_id"])
    op.create_index("ix_audit_findings_severity", "audit_findings", ["severity"])


def downgrade() -> None:
    op.drop_table("audit_findings")
    op.drop_table("audit_category_scores")
    op.drop_table("audit_results")
    op.drop_table("resume_uploads")
    op.drop_table("candidate_skills")
    op.drop_table("candidates")
